// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: api/protoapi-spec/sealet/v1/api.proto

package v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SeaLetServiceClient is the client API for SeaLetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeaLetServiceClient interface {
}

type seaLetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeaLetServiceClient(cc grpc.ClientConnInterface) SeaLetServiceClient {
	return &seaLetServiceClient{cc}
}

// SeaLetServiceServer is the server API for SeaLetService service.
// All implementations must embed UnimplementedSeaLetServiceServer
// for forward compatibility
type SeaLetServiceServer interface {
	mustEmbedUnimplementedSeaLetServiceServer()
}

// UnimplementedSeaLetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSeaLetServiceServer struct {
}

func (UnimplementedSeaLetServiceServer) mustEmbedUnimplementedSeaLetServiceServer() {}

// UnsafeSeaLetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeaLetServiceServer will
// result in compilation errors.
type UnsafeSeaLetServiceServer interface {
	mustEmbedUnimplementedSeaLetServiceServer()
}

func RegisterSeaLetServiceServer(s grpc.ServiceRegistrar, srv SeaLetServiceServer) {
	s.RegisterService(&SeaLetService_ServiceDesc, srv)
}

// SeaLetService_ServiceDesc is the grpc.ServiceDesc for SeaLetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeaLetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sea.api.sealet.v1.SeaLetService",
	HandlerType: (*SeaLetServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/protoapi-spec/sealet/v1/api.proto",
}
