// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/protoapi-spec/sea-date/v1/api.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取当前时间请求
type NowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求ID
	RequestId     string `protobuf:"bytes,1,opt,name=request_id,json=RequestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NowRequest) Reset() {
	*x = NowRequest{}
	mi := &file_api_protoapi_spec_sea_date_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowRequest) ProtoMessage() {}

func (x *NowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protoapi_spec_sea_date_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowRequest.ProtoReflect.Descriptor instead.
func (*NowRequest) Descriptor() ([]byte, []int) {
	return file_api_protoapi_spec_sea_date_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *NowRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// 获取当前时间响应
type NowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 错误码（0 表示成功）
	Code int32 `protobuf:"varint,1,opt,name=code,json=Code,proto3" json:"code,omitempty"`
	// 错误信息
	Message string `protobuf:"bytes,2,opt,name=message,json=Message,proto3" json:"message,omitempty"`
	// 当前时间
	Date          string `protobuf:"bytes,3,opt,name=date,json=Date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NowResponse) Reset() {
	*x = NowResponse{}
	mi := &file_api_protoapi_spec_sea_date_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowResponse) ProtoMessage() {}

func (x *NowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protoapi_spec_sea_date_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowResponse.ProtoReflect.Descriptor instead.
func (*NowResponse) Descriptor() ([]byte, []int) {
	return file_api_protoapi_spec_sea_date_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *NowResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NowResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// 获取当前时间（模拟错误）请求
type NowErrorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求ID
	RequestId     string `protobuf:"bytes,1,opt,name=request_id,json=RequestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NowErrorRequest) Reset() {
	*x = NowErrorRequest{}
	mi := &file_api_protoapi_spec_sea_date_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NowErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowErrorRequest) ProtoMessage() {}

func (x *NowErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_protoapi_spec_sea_date_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowErrorRequest.ProtoReflect.Descriptor instead.
func (*NowErrorRequest) Descriptor() ([]byte, []int) {
	return file_api_protoapi_spec_sea_date_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *NowErrorRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// 获取当前时间（模拟错误）响应
type NowErrorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 错误码（0 表示成功）
	Code int32 `protobuf:"varint,1,opt,name=code,json=Code,proto3" json:"code,omitempty"`
	// 错误信息
	Message string `protobuf:"bytes,2,opt,name=message,json=Message,proto3" json:"message,omitempty"`
	// 当前时间
	Date          string `protobuf:"bytes,3,opt,name=date,json=Date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NowErrorResponse) Reset() {
	*x = NowErrorResponse{}
	mi := &file_api_protoapi_spec_sea_date_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NowErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NowErrorResponse) ProtoMessage() {}

func (x *NowErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_protoapi_spec_sea_date_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NowErrorResponse.ProtoReflect.Descriptor instead.
func (*NowErrorResponse) Descriptor() ([]byte, []int) {
	return file_api_protoapi_spec_sea_date_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *NowErrorResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NowErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NowErrorResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_api_protoapi_spec_sea_date_v1_api_proto protoreflect.FileDescriptor

const file_api_protoapi_spec_sea_date_v1_api_proto_rawDesc = "" +
	"\n" +
	"'api/protoapi-spec/sea-date/v1/api.proto\x12\x0fsea.api.seadate\x1a\x1cgoogle/api/annotations.proto\"+\n" +
	"\n" +
	"NowRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\tRequestId\"O\n" +
	"\vNowResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04Code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\aMessage\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04Date\"0\n" +
	"\x0fNowErrorRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\tRequestId\"T\n" +
	"\x10NowErrorResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04Code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\aMessage\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04Date2\xd3\x01\n" +
	"\x0eSeaDateService\x12U\n" +
	"\x03Now\x12\x1b.sea.api.seadate.NowRequest\x1a\x1c.sea.api.seadate.NowResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/api/now\x12j\n" +
	"\bNowError\x12 .sea.api.seadate.NowErrorRequest\x1a!.sea.api.seadate.NowErrorResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/now_errorB8Z6github.com/kaydxh/sea/api/protoapi-spec/sea-date/v1;v1b\x06proto3"

var (
	file_api_protoapi_spec_sea_date_v1_api_proto_rawDescOnce sync.Once
	file_api_protoapi_spec_sea_date_v1_api_proto_rawDescData []byte
)

func file_api_protoapi_spec_sea_date_v1_api_proto_rawDescGZIP() []byte {
	file_api_protoapi_spec_sea_date_v1_api_proto_rawDescOnce.Do(func() {
		file_api_protoapi_spec_sea_date_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protoapi_spec_sea_date_v1_api_proto_rawDesc), len(file_api_protoapi_spec_sea_date_v1_api_proto_rawDesc)))
	})
	return file_api_protoapi_spec_sea_date_v1_api_proto_rawDescData
}

var file_api_protoapi_spec_sea_date_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_protoapi_spec_sea_date_v1_api_proto_goTypes = []any{
	(*NowRequest)(nil),       // 0: sea.api.seadate.NowRequest
	(*NowResponse)(nil),      // 1: sea.api.seadate.NowResponse
	(*NowErrorRequest)(nil),  // 2: sea.api.seadate.NowErrorRequest
	(*NowErrorResponse)(nil), // 3: sea.api.seadate.NowErrorResponse
}
var file_api_protoapi_spec_sea_date_v1_api_proto_depIdxs = []int32{
	0, // 0: sea.api.seadate.SeaDateService.Now:input_type -> sea.api.seadate.NowRequest
	2, // 1: sea.api.seadate.SeaDateService.NowError:input_type -> sea.api.seadate.NowErrorRequest
	1, // 2: sea.api.seadate.SeaDateService.Now:output_type -> sea.api.seadate.NowResponse
	3, // 3: sea.api.seadate.SeaDateService.NowError:output_type -> sea.api.seadate.NowErrorResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_protoapi_spec_sea_date_v1_api_proto_init() }
func file_api_protoapi_spec_sea_date_v1_api_proto_init() {
	if File_api_protoapi_spec_sea_date_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protoapi_spec_sea_date_v1_api_proto_rawDesc), len(file_api_protoapi_spec_sea_date_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_protoapi_spec_sea_date_v1_api_proto_goTypes,
		DependencyIndexes: file_api_protoapi_spec_sea_date_v1_api_proto_depIdxs,
		MessageInfos:      file_api_protoapi_spec_sea_date_v1_api_proto_msgTypes,
	}.Build()
	File_api_protoapi_spec_sea_date_v1_api_proto = out.File
	file_api_protoapi_spec_sea_date_v1_api_proto_goTypes = nil
	file_api_protoapi_spec_sea_date_v1_api_proto_depIdxs = nil
}
