// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: api/protoapi-spec/sea-date/v1/api.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SeaDateServiceClient is the client API for SeaDateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeaDateServiceClient interface {
	// 生成当前时间
	Now(ctx context.Context, in *NowRequest, opts ...grpc.CallOption) (*NowResponse, error)
	NowError(ctx context.Context, in *NowErrorRequest, opts ...grpc.CallOption) (*NowErrorResponse, error)
}

type seaDateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSeaDateServiceClient(cc grpc.ClientConnInterface) SeaDateServiceClient {
	return &seaDateServiceClient{cc}
}

func (c *seaDateServiceClient) Now(ctx context.Context, in *NowRequest, opts ...grpc.CallOption) (*NowResponse, error) {
	out := new(NowResponse)
	err := c.cc.Invoke(ctx, "/sea.api.seadate.SeaDateService/Now", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seaDateServiceClient) NowError(ctx context.Context, in *NowErrorRequest, opts ...grpc.CallOption) (*NowErrorResponse, error) {
	out := new(NowErrorResponse)
	err := c.cc.Invoke(ctx, "/sea.api.seadate.SeaDateService/NowError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeaDateServiceServer is the server API for SeaDateService service.
// All implementations must embed UnimplementedSeaDateServiceServer
// for forward compatibility
type SeaDateServiceServer interface {
	// 生成当前时间
	Now(context.Context, *NowRequest) (*NowResponse, error)
	NowError(context.Context, *NowErrorRequest) (*NowErrorResponse, error)
	mustEmbedUnimplementedSeaDateServiceServer()
}

// UnimplementedSeaDateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSeaDateServiceServer struct {
}

func (UnimplementedSeaDateServiceServer) Now(context.Context, *NowRequest) (*NowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Now not implemented")
}
func (UnimplementedSeaDateServiceServer) NowError(context.Context, *NowErrorRequest) (*NowErrorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NowError not implemented")
}
func (UnimplementedSeaDateServiceServer) mustEmbedUnimplementedSeaDateServiceServer() {}

// UnsafeSeaDateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeaDateServiceServer will
// result in compilation errors.
type UnsafeSeaDateServiceServer interface {
	mustEmbedUnimplementedSeaDateServiceServer()
}

func RegisterSeaDateServiceServer(s grpc.ServiceRegistrar, srv SeaDateServiceServer) {
	s.RegisterService(&SeaDateService_ServiceDesc, srv)
}

func _SeaDateService_Now_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeaDateServiceServer).Now(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sea.api.seadate.SeaDateService/Now",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeaDateServiceServer).Now(ctx, req.(*NowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SeaDateService_NowError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NowErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeaDateServiceServer).NowError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sea.api.seadate.SeaDateService/NowError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeaDateServiceServer).NowError(ctx, req.(*NowErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SeaDateService_ServiceDesc is the grpc.ServiceDesc for SeaDateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SeaDateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sea.api.seadate.SeaDateService",
	HandlerType: (*SeaDateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Now",
			Handler:    _SeaDateService_Now_Handler,
		},
		{
			MethodName: "NowError",
			Handler:    _SeaDateService_NowError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/protoapi-spec/sea-date/v1/api.proto",
}
