// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/protoapi-spec/sea-date/v1/configuration.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// config file yaml
type Configuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Debug         *Configuration_Debug   `protobuf:"bytes,20,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_api_protoapi_spec_sea_date_v1_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_api_protoapi_spec_sea_date_v1_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_api_protoapi_spec_sea_date_v1_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *Configuration) GetDebug() *Configuration_Debug {
	if x != nil {
		return x.Debug
	}
	return nil
}

type Configuration_Debug struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Dump          *Configuration_Debug_Dump `protobuf:"bytes,1,opt,name=dump,proto3" json:"dump,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration_Debug) Reset() {
	*x = Configuration_Debug{}
	mi := &file_api_protoapi_spec_sea_date_v1_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_Debug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_Debug) ProtoMessage() {}

func (x *Configuration_Debug) ProtoReflect() protoreflect.Message {
	mi := &file_api_protoapi_spec_sea_date_v1_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration_Debug.ProtoReflect.Descriptor instead.
func (*Configuration_Debug) Descriptor() ([]byte, []int) {
	return file_api_protoapi_spec_sea_date_v1_configuration_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Configuration_Debug) GetDump() *Configuration_Debug_Dump {
	if x != nil {
		return x.Dump
	}
	return nil
}

type Configuration_Debug_Dump struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DumpDir       string                 `protobuf:"bytes,2,opt,name=dump_dir,json=dumpDir,proto3" json:"dump_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration_Debug_Dump) Reset() {
	*x = Configuration_Debug_Dump{}
	mi := &file_api_protoapi_spec_sea_date_v1_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration_Debug_Dump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration_Debug_Dump) ProtoMessage() {}

func (x *Configuration_Debug_Dump) ProtoReflect() protoreflect.Message {
	mi := &file_api_protoapi_spec_sea_date_v1_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration_Debug_Dump.ProtoReflect.Descriptor instead.
func (*Configuration_Debug_Dump) Descriptor() ([]byte, []int) {
	return file_api_protoapi_spec_sea_date_v1_configuration_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Configuration_Debug_Dump) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Configuration_Debug_Dump) GetDumpDir() string {
	if x != nil {
		return x.DumpDir
	}
	return ""
}

var File_api_protoapi_spec_sea_date_v1_configuration_proto protoreflect.FileDescriptor

const file_api_protoapi_spec_sea_date_v1_configuration_proto_rawDesc = "" +
	"\n" +
	"1api/protoapi-spec/sea-date/v1/configuration.proto\x12\x0fsea.api.seadate\x1a\x1egoogle/protobuf/duration.proto\"\xd1\x01\n" +
	"\rConfiguration\x12:\n" +
	"\x05debug\x18\x14 \x01(\v2$.sea.api.seadate.Configuration.DebugR\x05debug\x1a\x83\x01\n" +
	"\x05Debug\x12=\n" +
	"\x04dump\x18\x01 \x01(\v2).sea.api.seadate.Configuration.Debug.DumpR\x04dump\x1a;\n" +
	"\x04Dump\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x19\n" +
	"\bdump_dir\x18\x02 \x01(\tR\adumpDirB3Z1github.com/kaydxh/sea/protoapi-spec/seadate/v1;v1b\x06proto3"

var (
	file_api_protoapi_spec_sea_date_v1_configuration_proto_rawDescOnce sync.Once
	file_api_protoapi_spec_sea_date_v1_configuration_proto_rawDescData []byte
)

func file_api_protoapi_spec_sea_date_v1_configuration_proto_rawDescGZIP() []byte {
	file_api_protoapi_spec_sea_date_v1_configuration_proto_rawDescOnce.Do(func() {
		file_api_protoapi_spec_sea_date_v1_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protoapi_spec_sea_date_v1_configuration_proto_rawDesc), len(file_api_protoapi_spec_sea_date_v1_configuration_proto_rawDesc)))
	})
	return file_api_protoapi_spec_sea_date_v1_configuration_proto_rawDescData
}

var file_api_protoapi_spec_sea_date_v1_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_protoapi_spec_sea_date_v1_configuration_proto_goTypes = []any{
	(*Configuration)(nil),            // 0: sea.api.seadate.Configuration
	(*Configuration_Debug)(nil),      // 1: sea.api.seadate.Configuration.Debug
	(*Configuration_Debug_Dump)(nil), // 2: sea.api.seadate.Configuration.Debug.Dump
}
var file_api_protoapi_spec_sea_date_v1_configuration_proto_depIdxs = []int32{
	1, // 0: sea.api.seadate.Configuration.debug:type_name -> sea.api.seadate.Configuration.Debug
	2, // 1: sea.api.seadate.Configuration.Debug.dump:type_name -> sea.api.seadate.Configuration.Debug.Dump
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_protoapi_spec_sea_date_v1_configuration_proto_init() }
func file_api_protoapi_spec_sea_date_v1_configuration_proto_init() {
	if File_api_protoapi_spec_sea_date_v1_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protoapi_spec_sea_date_v1_configuration_proto_rawDesc), len(file_api_protoapi_spec_sea_date_v1_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protoapi_spec_sea_date_v1_configuration_proto_goTypes,
		DependencyIndexes: file_api_protoapi_spec_sea_date_v1_configuration_proto_depIdxs,
		MessageInfos:      file_api_protoapi_spec_sea_date_v1_configuration_proto_msgTypes,
	}.Build()
	File_api_protoapi_spec_sea_date_v1_configuration_proto = out.File
	file_api_protoapi_spec_sea_date_v1_configuration_proto_goTypes = nil
	file_api_protoapi_spec_sea_date_v1_configuration_proto_depIdxs = nil
}
