// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.13.0
// source: api/protoapi-spec/sea-date/v1/error.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum describing possible face fusion reasons.
// Enum 描述了人脸融合业务出错的可能原因 -- 映射为具体业务错误码
// 大驼峰式命名法
// 一二级错误码之间用'_'隔开，服务会自动将之转换为'.'
type SeaDateReasonEnum_SeaDateReason int32

const (
	// The canonical error codes for gRPC APIs.
	// https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto
	SeaDateReasonEnum_OK                SeaDateReasonEnum_SeaDateReason = 0 // 无错误
	SeaDateReasonEnum_CANCELLED         SeaDateReasonEnum_SeaDateReason = 1 // 请求被客户端取消
	SeaDateReasonEnum_UNKNOWN           SeaDateReasonEnum_SeaDateReason = 2 // 出现未知的服务器错误。通常是服务器错误。
	SeaDateReasonEnum_INVALID_ARGUMENT  SeaDateReasonEnum_SeaDateReason = 3 // 客户端指定了无效参数。如需了解详情，请查看错误消息和错误详细信息
	SeaDateReasonEnum_DEADLINE_EXCEEDED SeaDateReasonEnum_SeaDateReason = 4 // 超出请求时限。仅当调用者设置的时限比方法的默认时限短（即请求的时限不足以让服务器处理请求）并且请求未在时限范围内完成时，才会发生这种情况
	SeaDateReasonEnum_NOT_FOUND         SeaDateReasonEnum_SeaDateReason = 5 // 未找到指定的资源
	SeaDateReasonEnum_ALREADY_EXISTS    SeaDateReasonEnum_SeaDateReason = 6 // 客户端尝试创建的资源已存在
	SeaDateReasonEnum_PERMISSION_DENIED SeaDateReasonEnum_SeaDateReason = 7 // 客户端权限不足。这可能是因为 OAuth
	// 令牌没有正确的范围、客户端没有权限或者 API 尚未启用
	SeaDateReasonEnum_UNAUTHENTICATED     SeaDateReasonEnum_SeaDateReason = 16 // 由于 OAuth 令牌丢失、无效或过期，请求未通过身份验证
	SeaDateReasonEnum_RESOURCE_EXHAUSTED  SeaDateReasonEnum_SeaDateReason = 8  // 资源配额不足或达到速率限制。如需了解详情，请查看错误消息和错误详细信息
	SeaDateReasonEnum_FAILED_PRECONDITION SeaDateReasonEnum_SeaDateReason = 9  // 请求无法在当前系统状态下执行，例如删除非空目录
	SeaDateReasonEnum_ABORTED             SeaDateReasonEnum_SeaDateReason = 10 // 并发冲突，例如读取/修改/写入冲突
	SeaDateReasonEnum_OUT_OF_RANGE        SeaDateReasonEnum_SeaDateReason = 11 // 客户端指定了无效范围
	SeaDateReasonEnum_UNIMPLEMENTED       SeaDateReasonEnum_SeaDateReason = 12 // API 方法未通过服务器实现
	SeaDateReasonEnum_INTERNAL            SeaDateReasonEnum_SeaDateReason = 13 // 出现内部服务器错误。通常是服务器错误
	SeaDateReasonEnum_UNAVAILABLE         SeaDateReasonEnum_SeaDateReason = 14 // 服务不可用。通常是服务器已关闭
	SeaDateReasonEnum_DATA_LOSS           SeaDateReasonEnum_SeaDateReason = 15 // 出现不可恢复的数据丢失或数据损坏。客户端应该向用户报告错误
	SeaDateReasonEnum_InvalidParameter    SeaDateReasonEnum_SeaDateReason = 1000
)

// Enum value maps for SeaDateReasonEnum_SeaDateReason.
var (
	SeaDateReasonEnum_SeaDateReason_name = map[int32]string{
		0:    "OK",
		1:    "CANCELLED",
		2:    "UNKNOWN",
		3:    "INVALID_ARGUMENT",
		4:    "DEADLINE_EXCEEDED",
		5:    "NOT_FOUND",
		6:    "ALREADY_EXISTS",
		7:    "PERMISSION_DENIED",
		16:   "UNAUTHENTICATED",
		8:    "RESOURCE_EXHAUSTED",
		9:    "FAILED_PRECONDITION",
		10:   "ABORTED",
		11:   "OUT_OF_RANGE",
		12:   "UNIMPLEMENTED",
		13:   "INTERNAL",
		14:   "UNAVAILABLE",
		15:   "DATA_LOSS",
		1000: "InvalidParameter",
	}
	SeaDateReasonEnum_SeaDateReason_value = map[string]int32{
		"OK":                  0,
		"CANCELLED":           1,
		"UNKNOWN":             2,
		"INVALID_ARGUMENT":    3,
		"DEADLINE_EXCEEDED":   4,
		"NOT_FOUND":           5,
		"ALREADY_EXISTS":      6,
		"PERMISSION_DENIED":   7,
		"UNAUTHENTICATED":     16,
		"RESOURCE_EXHAUSTED":  8,
		"FAILED_PRECONDITION": 9,
		"ABORTED":             10,
		"OUT_OF_RANGE":        11,
		"UNIMPLEMENTED":       12,
		"INTERNAL":            13,
		"UNAVAILABLE":         14,
		"DATA_LOSS":           15,
		"InvalidParameter":    1000,
	}
)

func (x SeaDateReasonEnum_SeaDateReason) Enum() *SeaDateReasonEnum_SeaDateReason {
	p := new(SeaDateReasonEnum_SeaDateReason)
	*p = x
	return p
}

func (x SeaDateReasonEnum_SeaDateReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeaDateReasonEnum_SeaDateReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protoapi_spec_sea_date_v1_error_proto_enumTypes[0].Descriptor()
}

func (SeaDateReasonEnum_SeaDateReason) Type() protoreflect.EnumType {
	return &file_api_protoapi_spec_sea_date_v1_error_proto_enumTypes[0]
}

func (x SeaDateReasonEnum_SeaDateReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeaDateReasonEnum_SeaDateReason.Descriptor instead.
func (SeaDateReasonEnum_SeaDateReason) EnumDescriptor() ([]byte, []int) {
	return file_api_protoapi_spec_sea_date_v1_error_proto_rawDescGZIP(), []int{0, 0}
}

type SeaDateReasonEnum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SeaDateReasonEnum) Reset() {
	*x = SeaDateReasonEnum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_protoapi_spec_sea_date_v1_error_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeaDateReasonEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeaDateReasonEnum) ProtoMessage() {}

func (x *SeaDateReasonEnum) ProtoReflect() protoreflect.Message {
	mi := &file_api_protoapi_spec_sea_date_v1_error_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeaDateReasonEnum.ProtoReflect.Descriptor instead.
func (*SeaDateReasonEnum) Descriptor() ([]byte, []int) {
	return file_api_protoapi_spec_sea_date_v1_error_proto_rawDescGZIP(), []int{0}
}

var File_api_protoapi_spec_sea_date_v1_error_proto protoreflect.FileDescriptor

var file_api_protoapi_spec_sea_date_v1_error_proto_rawDesc = []byte{
	0x0a, 0x29, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61, 0x70, 0x69, 0x2d, 0x73,
	0x70, 0x65, 0x63, 0x2f, 0x73, 0x65, 0x61, 0x2d, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x73, 0x65, 0x61,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x73, 0x65, 0x61, 0x64, 0x61, 0x74, 0x65, 0x22, 0xed, 0x02, 0x0a,
	0x11, 0x53, 0x65, 0x61, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x45, 0x6e,
	0x75, 0x6d, 0x22, 0xd7, 0x02, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x44, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x41, 0x52, 0x47, 0x55, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x03, 0x12, 0x15,
	0x0a, 0x11, 0x44, 0x45, 0x41, 0x44, 0x4c, 0x49, 0x4e, 0x45, 0x5f, 0x45, 0x58, 0x43, 0x45, 0x45,
	0x44, 0x45, 0x44, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55,
	0x4e, 0x44, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f,
	0x45, 0x58, 0x49, 0x53, 0x54, 0x53, 0x10, 0x06, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x45, 0x52, 0x4d,
	0x49, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x4e, 0x49, 0x45, 0x44, 0x10, 0x07, 0x12,
	0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54,
	0x45, 0x44, 0x10, 0x10, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45,
	0x5f, 0x45, 0x58, 0x48, 0x41, 0x55, 0x53, 0x54, 0x45, 0x44, 0x10, 0x08, 0x12, 0x17, 0x0a, 0x13,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x50, 0x52, 0x45, 0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54,
	0x49, 0x4f, 0x4e, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x42, 0x4f, 0x52, 0x54, 0x45, 0x44,
	0x10, 0x0a, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x55, 0x54, 0x5f, 0x4f, 0x46, 0x5f, 0x52, 0x41, 0x4e,
	0x47, 0x45, 0x10, 0x0b, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x4e, 0x49, 0x4d, 0x50, 0x4c, 0x45, 0x4d,
	0x45, 0x4e, 0x54, 0x45, 0x44, 0x10, 0x0c, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x54, 0x45, 0x52,
	0x4e, 0x41, 0x4c, 0x10, 0x0d, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x41, 0x56, 0x41, 0x49, 0x4c,
	0x41, 0x42, 0x4c, 0x45, 0x10, 0x0e, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x4c,
	0x4f, 0x53, 0x53, 0x10, 0x0f, 0x12, 0x15, 0x0a, 0x10, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x10, 0xe8, 0x07, 0x42, 0x37, 0x5a, 0x35,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x61, 0x79, 0x64, 0x78,
	0x68, 0x2f, 0x73, 0x65, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x61,
	0x70, 0x69, 0x2d, 0x73, 0x70, 0x65, 0x63, 0x2f, 0x73, 0x65, 0x61, 0x64, 0x61, 0x74, 0x65, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_protoapi_spec_sea_date_v1_error_proto_rawDescOnce sync.Once
	file_api_protoapi_spec_sea_date_v1_error_proto_rawDescData = file_api_protoapi_spec_sea_date_v1_error_proto_rawDesc
)

func file_api_protoapi_spec_sea_date_v1_error_proto_rawDescGZIP() []byte {
	file_api_protoapi_spec_sea_date_v1_error_proto_rawDescOnce.Do(func() {
		file_api_protoapi_spec_sea_date_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_protoapi_spec_sea_date_v1_error_proto_rawDescData)
	})
	return file_api_protoapi_spec_sea_date_v1_error_proto_rawDescData
}

var file_api_protoapi_spec_sea_date_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_protoapi_spec_sea_date_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_protoapi_spec_sea_date_v1_error_proto_goTypes = []interface{}{
	(SeaDateReasonEnum_SeaDateReason)(0), // 0: sea.api.seadate.SeaDateReasonEnum.SeaDateReason
	(*SeaDateReasonEnum)(nil),            // 1: sea.api.seadate.SeaDateReasonEnum
}
var file_api_protoapi_spec_sea_date_v1_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_protoapi_spec_sea_date_v1_error_proto_init() }
func file_api_protoapi_spec_sea_date_v1_error_proto_init() {
	if File_api_protoapi_spec_sea_date_v1_error_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_protoapi_spec_sea_date_v1_error_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeaDateReasonEnum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_protoapi_spec_sea_date_v1_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protoapi_spec_sea_date_v1_error_proto_goTypes,
		DependencyIndexes: file_api_protoapi_spec_sea_date_v1_error_proto_depIdxs,
		EnumInfos:         file_api_protoapi_spec_sea_date_v1_error_proto_enumTypes,
		MessageInfos:      file_api_protoapi_spec_sea_date_v1_error_proto_msgTypes,
	}.Build()
	File_api_protoapi_spec_sea_date_v1_error_proto = out.File
	file_api_protoapi_spec_sea_date_v1_error_proto_rawDesc = nil
	file_api_protoapi_spec_sea_date_v1_error_proto_goTypes = nil
	file_api_protoapi_spec_sea_date_v1_error_proto_depIdxs = nil
}
