// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/protoapi-spec/sea-date/v1/error.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum describing possible face fusion reasons.
// Enum 描述了人脸融合业务出错的可能原因 -- 映射为具体业务错误码
// 大驼峰式命名法
// 一二级错误码之间用'_'隔开，服务会自动将之转换为'.'
type SeaDateReasonEnum_SeaDateReason int32

const (
	// The canonical error codes for gRPC APIs.
	// https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto
	SeaDateReasonEnum_OK                SeaDateReasonEnum_SeaDateReason = 0 // 无错误
	SeaDateReasonEnum_CANCELLED         SeaDateReasonEnum_SeaDateReason = 1 // 请求被客户端取消
	SeaDateReasonEnum_UNKNOWN           SeaDateReasonEnum_SeaDateReason = 2 // 出现未知的服务器错误。通常是服务器错误。
	SeaDateReasonEnum_INVALID_ARGUMENT  SeaDateReasonEnum_SeaDateReason = 3 // 客户端指定了无效参数。如需了解详情，请查看错误消息和错误详细信息
	SeaDateReasonEnum_DEADLINE_EXCEEDED SeaDateReasonEnum_SeaDateReason = 4 // 超出请求时限。仅当调用者设置的时限比方法的默认时限短（即请求的时限不足以让服务器处理请求）并且请求未在时限范围内完成时，才会发生这种情况
	SeaDateReasonEnum_NOT_FOUND         SeaDateReasonEnum_SeaDateReason = 5 // 未找到指定的资源
	SeaDateReasonEnum_ALREADY_EXISTS    SeaDateReasonEnum_SeaDateReason = 6 // 客户端尝试创建的资源已存在
	SeaDateReasonEnum_PERMISSION_DENIED SeaDateReasonEnum_SeaDateReason = 7 // 客户端权限不足。这可能是因为 OAuth
	// 令牌没有正确的范围、客户端没有权限或者 API 尚未启用
	SeaDateReasonEnum_UNAUTHENTICATED     SeaDateReasonEnum_SeaDateReason = 16 // 由于 OAuth 令牌丢失、无效或过期，请求未通过身份验证
	SeaDateReasonEnum_RESOURCE_EXHAUSTED  SeaDateReasonEnum_SeaDateReason = 8  // 资源配额不足或达到速率限制。如需了解详情，请查看错误消息和错误详细信息
	SeaDateReasonEnum_FAILED_PRECONDITION SeaDateReasonEnum_SeaDateReason = 9  // 请求无法在当前系统状态下执行，例如删除非空目录
	SeaDateReasonEnum_ABORTED             SeaDateReasonEnum_SeaDateReason = 10 // 并发冲突，例如读取/修改/写入冲突
	SeaDateReasonEnum_OUT_OF_RANGE        SeaDateReasonEnum_SeaDateReason = 11 // 客户端指定了无效范围
	SeaDateReasonEnum_UNIMPLEMENTED       SeaDateReasonEnum_SeaDateReason = 12 // API 方法未通过服务器实现
	SeaDateReasonEnum_INTERNAL            SeaDateReasonEnum_SeaDateReason = 13 // 出现内部服务器错误。通常是服务器错误
	SeaDateReasonEnum_UNAVAILABLE         SeaDateReasonEnum_SeaDateReason = 14 // 服务不可用。通常是服务器已关闭
	SeaDateReasonEnum_DATA_LOSS           SeaDateReasonEnum_SeaDateReason = 15 // 出现不可恢复的数据丢失或数据损坏。客户端应该向用户报告错误
	SeaDateReasonEnum_InvalidParameter    SeaDateReasonEnum_SeaDateReason = 1000
)

// Enum value maps for SeaDateReasonEnum_SeaDateReason.
var (
	SeaDateReasonEnum_SeaDateReason_name = map[int32]string{
		0:    "OK",
		1:    "CANCELLED",
		2:    "UNKNOWN",
		3:    "INVALID_ARGUMENT",
		4:    "DEADLINE_EXCEEDED",
		5:    "NOT_FOUND",
		6:    "ALREADY_EXISTS",
		7:    "PERMISSION_DENIED",
		16:   "UNAUTHENTICATED",
		8:    "RESOURCE_EXHAUSTED",
		9:    "FAILED_PRECONDITION",
		10:   "ABORTED",
		11:   "OUT_OF_RANGE",
		12:   "UNIMPLEMENTED",
		13:   "INTERNAL",
		14:   "UNAVAILABLE",
		15:   "DATA_LOSS",
		1000: "InvalidParameter",
	}
	SeaDateReasonEnum_SeaDateReason_value = map[string]int32{
		"OK":                  0,
		"CANCELLED":           1,
		"UNKNOWN":             2,
		"INVALID_ARGUMENT":    3,
		"DEADLINE_EXCEEDED":   4,
		"NOT_FOUND":           5,
		"ALREADY_EXISTS":      6,
		"PERMISSION_DENIED":   7,
		"UNAUTHENTICATED":     16,
		"RESOURCE_EXHAUSTED":  8,
		"FAILED_PRECONDITION": 9,
		"ABORTED":             10,
		"OUT_OF_RANGE":        11,
		"UNIMPLEMENTED":       12,
		"INTERNAL":            13,
		"UNAVAILABLE":         14,
		"DATA_LOSS":           15,
		"InvalidParameter":    1000,
	}
)

func (x SeaDateReasonEnum_SeaDateReason) Enum() *SeaDateReasonEnum_SeaDateReason {
	p := new(SeaDateReasonEnum_SeaDateReason)
	*p = x
	return p
}

func (x SeaDateReasonEnum_SeaDateReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeaDateReasonEnum_SeaDateReason) Descriptor() protoreflect.EnumDescriptor {
	return file_api_protoapi_spec_sea_date_v1_error_proto_enumTypes[0].Descriptor()
}

func (SeaDateReasonEnum_SeaDateReason) Type() protoreflect.EnumType {
	return &file_api_protoapi_spec_sea_date_v1_error_proto_enumTypes[0]
}

func (x SeaDateReasonEnum_SeaDateReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeaDateReasonEnum_SeaDateReason.Descriptor instead.
func (SeaDateReasonEnum_SeaDateReason) EnumDescriptor() ([]byte, []int) {
	return file_api_protoapi_spec_sea_date_v1_error_proto_rawDescGZIP(), []int{0, 0}
}

type SeaDateReasonEnum struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeaDateReasonEnum) Reset() {
	*x = SeaDateReasonEnum{}
	mi := &file_api_protoapi_spec_sea_date_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeaDateReasonEnum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeaDateReasonEnum) ProtoMessage() {}

func (x *SeaDateReasonEnum) ProtoReflect() protoreflect.Message {
	mi := &file_api_protoapi_spec_sea_date_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeaDateReasonEnum.ProtoReflect.Descriptor instead.
func (*SeaDateReasonEnum) Descriptor() ([]byte, []int) {
	return file_api_protoapi_spec_sea_date_v1_error_proto_rawDescGZIP(), []int{0}
}

var File_api_protoapi_spec_sea_date_v1_error_proto protoreflect.FileDescriptor

const file_api_protoapi_spec_sea_date_v1_error_proto_rawDesc = "" +
	"\n" +
	")api/protoapi-spec/sea-date/v1/error.proto\x12\x0fsea.api.seadate\"\xed\x02\n" +
	"\x11SeaDateReasonEnum\"\xd7\x02\n" +
	"\rSeaDateReason\x12\x06\n" +
	"\x02OK\x10\x00\x12\r\n" +
	"\tCANCELLED\x10\x01\x12\v\n" +
	"\aUNKNOWN\x10\x02\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x03\x12\x15\n" +
	"\x11DEADLINE_EXCEEDED\x10\x04\x12\r\n" +
	"\tNOT_FOUND\x10\x05\x12\x12\n" +
	"\x0eALREADY_EXISTS\x10\x06\x12\x15\n" +
	"\x11PERMISSION_DENIED\x10\a\x12\x13\n" +
	"\x0fUNAUTHENTICATED\x10\x10\x12\x16\n" +
	"\x12RESOURCE_EXHAUSTED\x10\b\x12\x17\n" +
	"\x13FAILED_PRECONDITION\x10\t\x12\v\n" +
	"\aABORTED\x10\n" +
	"\x12\x10\n" +
	"\fOUT_OF_RANGE\x10\v\x12\x11\n" +
	"\rUNIMPLEMENTED\x10\f\x12\f\n" +
	"\bINTERNAL\x10\r\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x0e\x12\r\n" +
	"\tDATA_LOSS\x10\x0f\x12\x15\n" +
	"\x10InvalidParameter\x10\xe8\aB7Z5github.com/kaydxh/sea/api/protoapi-spec/seadate/v1;v1b\x06proto3"

var (
	file_api_protoapi_spec_sea_date_v1_error_proto_rawDescOnce sync.Once
	file_api_protoapi_spec_sea_date_v1_error_proto_rawDescData []byte
)

func file_api_protoapi_spec_sea_date_v1_error_proto_rawDescGZIP() []byte {
	file_api_protoapi_spec_sea_date_v1_error_proto_rawDescOnce.Do(func() {
		file_api_protoapi_spec_sea_date_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_protoapi_spec_sea_date_v1_error_proto_rawDesc), len(file_api_protoapi_spec_sea_date_v1_error_proto_rawDesc)))
	})
	return file_api_protoapi_spec_sea_date_v1_error_proto_rawDescData
}

var file_api_protoapi_spec_sea_date_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_protoapi_spec_sea_date_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_protoapi_spec_sea_date_v1_error_proto_goTypes = []any{
	(SeaDateReasonEnum_SeaDateReason)(0), // 0: sea.api.seadate.SeaDateReasonEnum.SeaDateReason
	(*SeaDateReasonEnum)(nil),            // 1: sea.api.seadate.SeaDateReasonEnum
}
var file_api_protoapi_spec_sea_date_v1_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_protoapi_spec_sea_date_v1_error_proto_init() }
func file_api_protoapi_spec_sea_date_v1_error_proto_init() {
	if File_api_protoapi_spec_sea_date_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_protoapi_spec_sea_date_v1_error_proto_rawDesc), len(file_api_protoapi_spec_sea_date_v1_error_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_protoapi_spec_sea_date_v1_error_proto_goTypes,
		DependencyIndexes: file_api_protoapi_spec_sea_date_v1_error_proto_depIdxs,
		EnumInfos:         file_api_protoapi_spec_sea_date_v1_error_proto_enumTypes,
		MessageInfos:      file_api_protoapi_spec_sea_date_v1_error_proto_msgTypes,
	}.Build()
	File_api_protoapi_spec_sea_date_v1_error_proto = out.File
	file_api_protoapi_spec_sea_date_v1_error_proto_goTypes = nil
	file_api_protoapi_spec_sea_date_v1_error_proto_depIdxs = nil
}
